TripLog1/Models/Trip.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace TripLog1.Models
{
    public class Trip
    {
        [Key]
        public int TripID { get; set; }

        [Required(ErrorMessage = "Please enter a Destination.")]
        public string Destination { get; set; }

        public string Accommodations { get; set; }


        [Required(ErrorMessage = "Please enter a trip start date.")]
        //[DataType(DataType.Date)]
        public DateTime? StartDate { get; set; }


        [Required(ErrorMessage = "Please enter a trip End date.")]
        //[DataType(DataType.Date)]
        public DateTime? EndDate { get; set; }


        public string Phone { get; set; }

        public string Email { get; set; }

        public string Things { get; set; }

        public string Things1 { get; set; }

        public string Things2 { get; set; }



       

    }
}

TripLog1/Models/TripContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;


namespace TripLog1.Models
{
    public class TripContext :  DbContext
    {
        public TripContext (DbContextOptions<TripContext> options) : base (options) { }
        
        public DbSet<Trip> Trips { get; set; }
        

        protected override void OnModelCreating(ModelBuilder modelBuilder)

        {
            modelBuilder.Entity<Trip>().HasData(
                
                new Trip
                {
                    TripID = 1,
                    Destination = "Boise",
                   // StartDate =DateTime.Parse("6/6/2020"),
                   // EndDate = DateTime.Parse("6/14/2020"),
                    Accommodations = "",
                    Things = " Visit Tammy",
                    Things1 = "",
                    Things2 = ""
                },

                new Trip
                {
                    TripID = 2,
                    Destination = "Portland",
                   // StartDate = DateTime.Parse("6/6/2020"),
                   // EndDate = DateTime.Parse("6/6/2020"),
                    Accommodations = "The Benson",
                    Phone = "503-555-1234",
                    Email = "staff@bensonhotel.com",
                    Things = "Go to Vodoo Doughnuts",
                    Things1 = "Walk in the rain",
                    Things2 = "Go to Powell's"
                }


                );
        }
       
    }
}

TripLog1/Controllers/AddController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TripLog1.Models;


namespace TripLog1.Controllers
{
    public class AddController : Controller
    {

        private TripContext context { get; set; }

        public AddController(TripContext ctx)
        {
            context = ctx;

        }

        [HttpGet]
        public IActionResult AddTrip()
        {
            ViewBag.Action = "Next"; 
            return View("AddTrip", new Trip());

        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AddInfo(int id)
        {
            ViewBag.Action = "Next";
            var AddTrip = context.Trips.Find(id);
            return View(AddTrip);
        }

        [HttpGet]
        public IActionResult AddThings(int id)
        {
            ViewBag.Action = "Next";
            var AddTrip = context.Trips.Find(id);
            return View(AddTrip);
        }

        [HttpPost]
        public IActionResult AddInfo( Trip addTrip)
        {
            if (ModelState.IsValid)
            {
                if (addTrip.Accommodations != null)
                    context.Trips.Add(addTrip);
                else
                    context.Trips.Update(addTrip);
                context.SaveChanges();
                return RedirectToAction("Next", "AddThings");      
            }
            else
            {
                ViewBag.Action = (addTrip.Accommodations == null) ? "Next":"Next" ;
                 return View(addTrip);
                ;
            }

        }

        [HttpPost]
        public IActionResult AddThings(Trip addTrip)
        {
            context.Trips.Update(addTrip);
            context.SaveChanges();
            return View(addTrip);
        }

      
    }
}

TripLog1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using TripLog1.Models;


namespace TripLog1.Controllers
{
    public class HomeController : Controller
    {

        private TripContext context { get; set; }

        public HomeController(TripContext ctx)
        {
            context = ctx;
        }

        public IActionResult Index(Trip trips)
        {

            
            return View(trips);
           

            
        }
        
          

       
    }
}

    

TripLog1/Views/Add/AddInfo.cshtml
@model Trip
@{
    string title = ViewBag.Action;
    ViewBag.Title = title;

}

    <div class="container">

        <h2>Add Info for</h2>
        <form asp-controller="Add" asp-action="AddThings" method="post">

            <div class="form-group">
                <label for="Phone">Phone Number</label>
                <input asp-for="Phone" class="form-control">
            </div>

            <div class="form-group">
                <label for="Email" >Email Address</label>
                <input asp-for="Email"class="form-control">
            </div>

            <input type="hidden" asp-for="TripID" />

            <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
            <a asp-controller="Home" asp-action="Index" class="btn btn-secondary">Cancel</a>
        </form>
    </div>

TripLog1/Views/Add/AddThings.cshtml
@model Trip
@{
    string title = ViewBag.Action;
    ViewBag.Title = title;

}


    <div class="container">

        <h2>Add Things To Do</h2>
        <form asp-controller="Add" asp-action="Index" method="post">

            <div class="form-group">
                <label for="Things" class="control-label"></label>
                <input asp-for="Things"class="form-control">
            </div>

            <div class="form-group">
                <label for="Things1" class="control-label"></label>
                <input asp-for="Things1"class="form-control">
            </div>

            <div class="form-group">
                <label for="Things2" class="control-label"></label>
                <input asp-for="Things2"class="form-control">
            </div>

            <input type="hidden" asp-for="TripID" />

            <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
            <a asp-controller="Home" asp-action="Index" class="btn btn-secondary">Cancel</a>
        </form>
    </div>

TripLog1/Views/Add/AddTrip.cshtml
@model Trip
@{
    string title = ViewBag.Action;
    ViewBag.Title =title;

}
   
    <div class="container">
      
        <h2>Add Trip Destination and Dates</h2>
        <form asp-controller="Add" asp-action="AddInfo" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-group">
                <label for="Destination">Destination</label>
                <input asp-for="Destination">
                
            </div>

            <div class="form-group">
                <label for="Accomodations">Accommodations</label>
                <input asp-for="Accommodations">
            </div>

            <div class="form-group">
                <label asp-for="StartDate">Start Date</label>
                <input type="text" asp-for="StartDate" >
              
            </div>

            <div class="form-group">
                <label asp-for="EndDate">End Date</label>
                <input type="text" asp-for="EndDate">
               
            </div>

            <input type="hidden" asp-for="TripID" />

            <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
            <a asp-controller="Home" asp-action="Index" class="btn btn-secondary">Cancel</a>
        </form>
    </div>

TripLog1/Views/Home/Index.cshtml
@model List<Trip>
@{ 
   ViewBag.Title = "My Trip Log";

}

    <div class="container">    

        <a asp-controller="Add" asp-action="AddTrip" ><b>Add Trip</b></a>

        <div class="row">
            <div class="col-sm-8">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Destination</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Accommodations</th>
                            <th>Things To Do</th>
                        </tr>                        
                    </thead>
                    <tbody>
                        @foreach (Trip addTrip in Model)
                         {
                            <tr>
                                <td>@addTrip.Destination</td>
                                <td>@addTrip.StartDate</td>
                                <td>@addTrip.EndDate</td>
                                <td>@addTrip.Accommodations <br />Phone: @addTrip.Phone | @addTrip.Email </td>
                                <td>@addTrip.Things<br /> @addTrip.Things1<br /> @addTrip.Things2</td>
                                    
                               
                                                                                              
                            </tr>

                    
                         }
           
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    

TripLog1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    
    <title>My Trip Log</title>
</head>
<body>
    <div class="container">
        <header class="jumbotron">
         <h1 class="text-center">My Trip Log</h1>
        
        </header>

        @RenderBody()
    </div>

</body>
</html>